### ISSUE TITLE
3/30 Team Meeting Notes

### ISSUE THREAD

**Issue by ticachica** [ivanfalala/GetLost#4]
### Attendees
- @ivanfalala 
- @moroxican-jay 
- @ticachica
### Agenda
- [ ] Create a user story
- [ ] Divide the work to implement user story
- [ ] Set next meeting date (2 weeks, around 4/13)
### The Story of Steve

Steve wants to get lost. Steve has a car and is in average shape. He is located in San Jose and wants to go on an adventure that is less than 40 miles away from his home. He opens up the GetLost app. Logs in with his Facebook login. The app asks him first how far is he willing to go. Then he enters the radius. Then apps ask how recreationally inclined is he. The choices are “Easy”, “Medium”, and “Hard”. Steve slides the slidebar to in between “Easy” and “Medium”. Then Steve selects the activities he likes or is interested in (like Pinterest). I.e. Hiking, Mountain Biking,  Road Biking, Swimming, Mountain climbing, walking, and running. He selects Mountain Biking, Hiking, and Walking. After checking all these, there will be a big button that shows “Get Lost”. Then show a map with little symbols for the different activities.  He can switch to list view where he can sort by “easiest to hardest” activities.  Chooses to take a walk and chooses the Almaden Trail activity. (Feature request:Link to FitBit) The activity page says advice on “What to do to maximize enjoyment”, “What to bring”, shows the current temperature, “Things to watch out for”. Also add altitude gain of the activity. 

At the end of doing the activity, Steve can get some positive reinforcement with badges and points. First badge “Newcomer” 

App should remember your miles and path in case Steve wants to do it again. 
### Work Plan
- [ ] @ivanfalala  - Look for open data about recreational activities and places to go
- [ ] @moroxican-jay  - will physically draw and build a story board. Put it on GitHub
- [ ] @ticachica - Can start building out the information architecture for the data we’ll need to populate the pages.
